### ISSUE TITLE
Switch to shields.io for badges?

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-internal#22]
So that the two badges use the same style. I can make a PR if everyone agrees.

**Comment by vladikoff** [comment]
would the badges look the same or is there a different appveyor badge? that might be a bit confusing if both look and say the same thing.

**Comment by XhmikosR** [comment]
We can specify the text to show. See the uncss repo for an example.

**Comment by XhmikosR** [comment]
So, any thoughts?

**Comment by XhmikosR** [comment]
Closing this for now since the badges look good now.
