### ISSUE TITLE
Travis: install npm only when node.js 0.10 is used

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-internal#26]
@shama: IIRC that's the only version we need it, right?

**Comment by XhmikosR** [comment]
@shama @vladikoff: This is what I have https://github.com/gruntjs/grunt-contrib-internal/compare/dev

Let me know if you agree or not. Alternatively, we could go with npm@2.

**Comment by XhmikosR** [comment]
On a side note, can someone add the git tag for 0.4.14?

**Comment by vladikoff** [comment]
I'll check this on Wednesday
