### ISSUE TITLE
GitHub Actions CI

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-internal#42]
@vladikoff can you register the org on GitHub Actions CI?

Then I could make the switch and we drop Travis and AppVeyor from all the repos.

**Comment by vladikoff** [comment]
that would be cool!

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/65776861-ec32f680-e110-11e9-8647-7b68a306603d.png)

**Comment by XhmikosR** [comment]
Perfect, I'll try experimenting with it. Note that I don't have push rights (nor npm publish rights in all the repos)

**Comment by vladikoff** [comment]
@XhmikosR you have at least one right?

**Comment by XhmikosR** [comment]
Not in all the repos.
